### ISSUE TITLE
personalizationIndex error

### ISSUE THREAD

**Issue by tomaston** [sendgrid/sendgrid-php#961] opened 2020-05-06 17:16 UTC
### Issue Summary
When trying to add a personalisation before sending any emails ('addTo'), I receive the below error regarding `personalizationIndex`.

### Code Snippet
```php
foreach ($users as $user_chunk) {
    $email = new \SendGrid\Mail\Mail();
    $sendgrid = new \SendGrid('APIKEY');
    $email->setFrom('from@email.com', 'From Name');
    $email->setTemplateId('TEMPLATEID');
    foreach ($user_chunk as $user) {
        $email->addTo(
            $user['user_email'],
            $user['user_email'],
            $substitutions,
            $i
        );
        $i++;
    }
    try {
        $response = $sendgrid->send($email);
    } catch (Exception $e) {
        die();
    }
}
```

### Exception/Log
```
personalizationIndex 1 must be less than 1
```

### Technical details:
* sendgrid-php version: 7.5.0
* php version: 7.4.5

**Comment by kampalex** [comment] 2020-05-11 14:42
I think outdated code and changed behavior is the cause of this issue.

In 7.5.0, when you construct `Mail` without arguments, only one `Personalization` at index 0 is available. If `$i` >0, it will report an error if you don't create additional `Personalization` instances.

I suggest to change the following parts:
Replace
```
$email = new \SendGrid\Mail\Mail();
[...]
$email->setFrom('from@email.com', 'From Name');
```
by
```
$from = new \SendGrid\Mail\From('from@email.com', 'From Name');
$email = new \SendGrid\Mail\Mail($from);
```
This will prevent creation of empty `Personalization`.

Replace inner `foreach` loop by next lines - it will create a `Personalization` instance per `$user`:
```
foreach ($user_chunk as $user) {
    $address = new To($user['user_email'], $user['user_email'], $substitutions);
    $personalization = new Personalization();
    $personalization->addTo($address);
    $email->addPersonalization($personalization);
}
```

**Comment by childish-sambino** [comment] 2020-05-18 18:58
Correct. I don't agree with the complexity here, but that's how it was built and many customers are currently using it as such. I'm open to reworking the backing implementation, but it will most likely be breaking for some users.

**Comment by kampalex** [comment] 2020-05-19 09:38
Currently, providing the `personalizationIndex` requires knowledge of existing indices of `Personalization` instances because these are used internally. This can be done by:
- `getPersonalizations()`, be careful, this method can also return `NULL` instead of empty array (must be fixed)
- `getPersonalizationCount()`, _assuming_ existing range [0...(result count-1)].

In the original code sample, `$i` hasn't been defined, assuming `$i` to be 0. It fails on `>0`.
In my code sample, `$i=0` isn't created yet (due to the way I construct `Mail`), so index 0 will fail.

Possible fix for original code sample may be permitting unknown/invalid `personalizationIndex` which indicates a new/different `Personalization` to create (or reuse if requested again). Provided index must be mapped to real index in `personalization` member. (I can work out a PR to indicate effects.)

**Comment by childish-sambino** [comment] 2020-05-28 15:18
@kampalex That works for me. Basically if the index is equal to the size of the array, create a new personalization and add it to the end. I can review the changes if you can submit.

**Comment by kampalex** [comment] 2020-05-28 18:54
Before submitting the PR, I have to create a few test assertions for `Personalization` handling which covers the optional usage of `personalizationIndex` and `personalization` arguments used in functions:
`addRecipientEmail`
`addRecipientEmails`
`setSubject`
`addHeader`
`addSubstitution`
`addCustomArg`
`setSendAt`

I was struggling and chose to create a variant which give users more control to use their own `personalizationIndex`. It supports current usage (like submitter of this issue has) but makes the internal handling more complicated.

- According to the docs, a `Personalization` must have at least a `To`, so when using `addTo` for nonexistent `personalizationIndex`, it makes sense to create a `Personalization` instance using `personalizationIndex`.
- If providing a `Personalization` using occupied `personalizationIndex`, properties may or must be merged. It will replace the existing `Personalization`.
- Except for using `addTo(s)` (or `addRecipientEmail(s)`), other functions must reject unknown `personalizationIndex`.

Bonus: I've implemented the `Personalization` limit of 1000 entries.

**Closed** 2020-06-15 15:32 UTC
Labels: difficulty: easy, status: help wanted, type: community enhancement
