### ISSUE TITLE
how to send list of images with addSubstitution

### ISSUE THREAD

**Issue by bduave** [sendgrid/sendgrid-php#486] opened 2017-10-16 14:43 UTC
I create list in php and then send it as a substitution but when I send images it displays as a code in the email not as image as we want. I created on our template modules as a code, text but and even text with image but when I send to those modules the information comes as the attached email. How can I send the code and convert as image?

#the code
`for ($z = 0; $z < count($ReturnListProdutcs); $z++) { 
    $ToList = $ReturnListProdutcs[$z]['Categoria'];
    $ToList1 = $ReturnListProdutcs[$z]['IdProduto'];
    $ShoppingList.=createHTMLBlock($ToList,$ToList1);
    
}
$mail->personalization[0]->addSubstitution("shopping_list", $ShoppingList);
function createHTMLBlock($ToList,$ToList1) {
        $str = "<div><img data-type='image' src='mydomain/images/produtos/$ToList/$ToList1.png'></div>";
        return htmlspecialchars($str);
    }
![1](https://user-images.githubusercontent.com/23331633/31618284-d55c0398-b291-11e7-9f84-b75fc031e53c.PNG)
`

**Comment by thinkingserious** [comment] 2017-10-16 18:10
Hello @bduave,

Do you mind sharing the code that sends the email? I'm trying to determine how you are building the email to be sent so that I can try to reproduce.

Thanks!

With Best Regards,

Elmer

**Comment by bduave** [comment] 2017-10-17 08:05
Hi @thinkingserious , thanks for reply.
i attached the files because when i paste here it hides some lines of code.

[Sendgrid.txt](https://github.com/sendgrid/sendgrid-php/files/1390234/Sendgrid.txt)

**Comment by mbernier** [comment] 2017-10-22 05:21
Hey @bduave - please go and change your API Key, since it was published in the .txt file you shared.

**Comment by mbernier** [comment] 2017-10-22 05:23
One thing I noticed in your code - 

`ReturnListProdutcs` might be a mispelling? `ReturnListProducts`
To test whether this is an issue, please try printing out `$ShoppingList` before you call this line:

```
$mail->personalization[0]->addSubstitution("shopping_list", $ShoppingList);
```

**Comment by devchas** [comment] 2017-10-23 22:31
Hey @bduave - when I ran a similar test, I found that the html substitutions containing image tags only worked when including the closing "/" in the image tag itself.  So, for example...

<img data-type="image" src="izyshop.co.mz/images/produtos/02/IMG0237010.png" />

instead of...

<img data-type="image" src="izyshop.co.mz/images/produtos/02/IMG0237010.png">

**Closed** 2018-02-27 23:17 UTC
Labels: hacktoberfest, status: help wanted, type: question
