### ISSUE TITLE
Name part in setFrom is wrapped in double quotes twice

### ISSUE THREAD

**Issue by bokibxs** [sendgrid/sendgrid-php#897] opened 2019-10-22 22:29 UTC
#### Issue Summary

Name part in setFrom is wrapped in double quotes twice, which results in incorrect From header and iOS Mail app not displaying from name properly.

#### Steps to Reproduce

Copy/paste Hello Email use case from here:
https://github.com/sendgrid/sendgrid-php
and replace this line:
`$email->setFrom("test@example.com", "Example User");`
with this:
`$email->setFrom("test@example.com", "Text, With, Commas");`
and output JSON before send call to see request body:
`echo json_encode($email, JSON_PRETTY_PRINT);`
and you'll get following:
```
{
    "personalizations": [
        {
            "to": [
                {
                    "name": "Example User",
                    "email": "test@example.com"
                }
            ]
        }
    ],
    "from": {
        "name": "\"Text, With, Commas\"",
        "email": "test@example.com"
    },
    "subject": "Sending with Twilio SendGrid is Fun",
    "content": [
        {
            "type": "text\/plain",
            "value": "and easy to do anywhere, even with PHP"
        },
        {
            "type": "text\/html",
            "value": "<strong>and easy to do anywhere, even with PHP<\/strong>"
        }
    ]
}
```

If you update emails and API key and send this out, this will result in From header name part like this:
`From: "\"Text, With, Commas\""`
And iOS Mail app will render that as attached.

![IMG_0138](https://user-images.githubusercontent.com/313137/67339764-d3dcae80-f4f9-11e9-9d2c-4e918bbfce0e.PNG)

#### Technical details:

* sendgrid-php Version: 7.3.0
* PHP Version: 7.2

**Comment by Harumaro** [comment] 2019-10-29 19:34
See #368 
https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/EmailAddress.php#L116
```
/*
            Issue #368
            ==========
            If the name is not wrapped in double quotes and contains a comma or
            semicolon, the API fails to parse it correctly.
            When wrapped in double quotes, commas, semicolons and unescaped single
            quotes are supported.
            Escaped double quotes are supported as well but will appear unescaped in
            the mail (e.g. "O\'Keefe").
            Double quotes will be shown in some email clients, so the name should
            only be wrapped when necessary.
        */
```

**Comment by bokibxs** [comment] 2019-10-29 19:37
Yep problem is that it is wrapped twice in double quotes, so instead of name resulting in:
"name": "Text, With, Commas",
It results in:
"name": "\"Text, With, Commas\"",

**Comment by childish-sambino** [comment] 2020-03-20 18:24
I took out the changes made in #511 and emails send fine. Checking to see if/when this was fixed on the back-end before committing to submitting a PR to revert the changes.

**Comment by childish-sambino** [comment] 2020-03-20 19:12
After checking with support turns out the original bug does not impact all customers/traffic, so I'm hesitant to take the double-quote wrapping fix out.

Another option is to make this configurable in the client so that you can make adjustments if you _know_ it's going to impact you or not.

I'll circle back here if it ever gets completely fixed on the backend so this code can be ripped out, but open to reviewing a PR if anyone wants to implements the option above.

**Comment by iant-ee** [comment] 2020-06-02 19:40
The original ticket that introduced this bug (#368) acknowledges that this is an API bug that only applies to V3, and @thinkingserious says that it is being fixed at the API level (but hadn't yet been, when 368 was being worked on).

Nowhere on #368, #370 or #511 do I see any mention of these quotes showing up in users email clients. I'd therefore suggest that at some point between those tickets being worked on and this ticket being filed that the underlying API bug was fixed, and this workaround should be reverted.

@childish-sambino Do you have any more information about which customers it does / does not impact? Is there a public bug report for the API-level bug? The response from support sounds like someone a support team might say if they knew that had seen a bug previously but couldn't reproduce it and hadn't been told it had been fixed.

**Closed** 2020-09-23 21:36 UTC
Labels: status: work in progress, type: community enhancement
