### ISSUE TITLE
Hello, i'm having trouble to setup a sendgrid form on a website. Getting error-> Fatal error: Uncaught Error: Class 'SendGrid\Mail' not found in C:\xampp\htdocs\WebApplication\signup.php:53 Stack trace: #0 {main} thrown in C:\xampp\htdocs\WebApplication\signup.php on line 53 #996

### ISSUE THREAD

**Issue by Timothy199** [sendgrid/sendgrid-php#997] opened 2020-08-11 19:00 UTC
<?php
    include 'DatabaseConnection.php';
    $dbConnection = DatabaseConnection::getInstance()->getConnection();
    require './vendor/autoload.php';
    //require 'lib/SendGrid/Email.php';
    $error = "";
    $password = "";
    $confirmedPassword = "";
    $email = "";
    $username = "";
    if ($_POST){
        if(!$_POST['username']){
            $error .= "A username is required.<br>";
        }else {
            $username = $_POST['username'];
        }
        if(!$_POST['email']){
          $error .= "An email address is required.<br>";
        }else{
            $email = $_POST['email'];
        }
        if(!$_POST['password']){
          $error .= "The password is required.<br>";
        }else{
            $password = $_POST['password'];
        }
        if(!$_POST['confirmPassword']){
            $error .= "Confirmation of your password is required.<br>";
        }else {
            $confirmedPassword = $_POST['confirmPassword'];
        }
        if(($_POST['confirmPassword'] && $_POST['password']) && $_POST['confirmPassword'] != $_POST['password']){
            $error .= "Passwords do not match.<br>";
        }
        if($_POST['email'] && filter_var($_POST['email'],FILTER_VALIDATE_EMAIL) == false){
          $error .= "The email address is invalid.<br>";
          $email = "";
        }else if ($_POST['email'] && filter_var($_POST['email'],FILTER_VALIDATE_EMAIL) == true){
            $query = "SELECT * FROM users WHERE `email` = '".$_POST['email']."'";
            if($rslt = mysqli_query($dbConnection, $query)) {
                if (mysqli_num_rows($rslt)) {
                    $error .= "An account with the same email address already exists. <br>";
                 }
            }
        }
        if($error != ""){
          $error = '<div class="signup-error" style="color:red;"><strong>Error:</strong><br>'.$error.'</div>';
        }else{
            $password_hash = password_hash($password, PASSWORD_DEFAULT);
            $query = "INSERT INTO `users` (`email`, `password`, `username`) VALUES ('".$email."', '".$password_hash."', '".$username."')";
            mysqli_query($dbConnection, $query);
            $link = "https://myunimarket.herokuapp.com/WebApplication/verify-email.php?user=".$email;
            $from = new SendGrid\Mail(null, "myunimarket@outlook.com");
            $subject = "Verify your email - MyUniMarket";
            $to = new SendGrid\Mail(null, $email);
            $content = new SendGrid\Content("text/html", "<p>Please confirm your email for MyUniMarket by clicking on this: ".$link."<p>");
            $mail = new SendGrid\Mail($from, $subject, $to, $content);
            $apiKey = getenv('SENDGRID_API_KEY');
            $sg = new \SendGrid($apiKey);
            $response = $sg->client->mail()->send()->post($mail);
            header('Location: signin.php');
        }
    }
?>

**Comment by thinkingserious** [comment] 2020-08-12 18:42
Duplicate of https://github.com/sendgrid/sendgrid-php/issues/996

**Closed by thinkingserious** 2020-08-12 18:42 UTC
