### ISSUE TITLE
How I can send Unique Arguments using newest version of API Lib?

### ISSUE THREAD

**Issue by michalper** [sendgrid/sendgrid-php#414] opened 2017-07-26 12:02 UTC
#### Issue Summary

How I can send the Unique Arguments via the latest version of SendGrid API without using X-SMTPAPI Header. https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html# the last part.

I have to get unique arguments via webhook response to save email status. 

My Mail object is:

`{
  "from": {
    "name": "=?UTF-8?B?aVByZXNzbw==?=",
    "email": "michal.per@ipresso.com"
  },
  "personalizations": [
    {
      "to": [
        {
          "name": "=?UTF-8?B?aVByZXNzbw==?=",
          "email": "michal.per@ipresso.com"
        }
      ]
    },
    {
      "to": [
        {
          "name": "=?utf-8?B?TWljaGHFgiBQZXI=?=",
          "email": "michal.per@encja.com"
        }
      ],
      "substitutions": {
        "-dmid-": 7,
        "-cid-": 696969,
        "-test-": true,
        "{firstName}": "First",
        "{lastName}": "Last",
        "{mail}": "michal.per@encja.com"
      }
    }
  ],
  "subject": "=?UTF-8?B?c3ViamVjdA==?=",
  "content": [
    {
      "type": "text/plain",
      "value": "{firstName} {lastName} {mail} test!"
    },
    {
      "type": "text/html",
      "value": "{firstName} {lastName} {mail} test!"
    }
  ],
  "custom_args": {
    "cmrid": "3",
    "dmcid": "69",
    "env": "prod",
    "dmid": "-dmid-",
    "cid": "-cid-",
    "test": "-test-"
  },
  "reply_to": {
    "email": "michal.per@ipresso.com"
  }
}`

and response:

`

SendGrid\Response Object
(
    [statusCode:protected] => 400
    [body:protected] => {"errors":[{"message":"Bad Request","field":null,"help":null}]}
    [headers:protected] => Array
        (
            [0] => HTTP/1.1 400 Bad Request
            [1] => Server: nginx
            [2] => Date: Wed, 26 Jul 2017 11:59:49 GMT
            [3] => Content-Type: application/json
            [4] => Content-Length: 63
            [5] => Connection: keep-alive
            [6] => X-Frame-Options: DENY
            [7] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
            [8] => Access-Control-Allow-Methods: POST
            [9] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
            [10] => Access-Control-Max-Age: 600
            [11] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
            [12] => 
            [13] => 
        )

)
`

#### Technical details:

* sendgrid-php Version: 6.0.0
* PHP Version: 7.0

**Comment by thinkingserious** [comment] 2017-07-27 02:01
Hello @michalper,

They are called CustomArgs and they can be set as show in [this full example](https://github.com/sendgrid/sendgrid-php/blob/master/examples/helpers/mail/example.php#L46). I hope that helps!

With Best Regards,

Elmer

**Comment by michalper** [comment] 2017-07-27 05:56
@thinkingserious yes Elmer, I've tested them and they not working. 
In my response SendGrid webhook they aren't parsed.

**Comment by thinkingserious** [comment] 2017-07-27 06:00
@michalper,

Were you able to get past the 400 error?

I think you need to change:

```json
      "substitutions": {
        "-cid-": 696969,
        "-dmid-": 7,
        "-test-": true,
        "{firstName}": "First",
        "{lastName}": "Last",
        "{mail}": "michal.per@encja.com"
      }
```

to

```json
      "substitutions": {
        "-cid-": "696969",
        "-dmid-": "7",
        "-test-": "true",
        "{firstName}": "First",
        "{lastName}": "Last",
        "{mail}": "michal.per@encja.com"
      }
```

**Comment by michalper** [comment] 2017-07-27 06:03
@thinkingserious 
I'm using API Lib full Mail objects:
SendGrid\Mail Object
(
    [namespace:protected] => SendGrid
    [from] => SendGrid\Email Object
        (
            [name:SendGrid\Email:private] => =?UTF-8?B?aVByZXNzbw==?=
            [email:SendGrid\Email:private] => michal.per@ipresso.com
        )

    [personalization] => Array
        (
            [0] => SendGrid\Personalization Object
                (
                    [tos:SendGrid\Personalization:private] => Array
                        (
                            [0] => SendGrid\Email Object
                                (
                                    [name:SendGrid\Email:private] => =?UTF-8?B?aVByZXNzbw==?=
                                    [email:SendGrid\Email:private] => michal.per@ipresso.com
                                )

                        )

                    [ccs:SendGrid\Personalization:private] => 
                    [bccs:SendGrid\Personalization:private] => 
                    [subject:SendGrid\Personalization:private] => 
                    [headers:SendGrid\Personalization:private] => 
                    [substitutions:SendGrid\Personalization:private] => 
                    [custom_args:SendGrid\Personalization:private] => 
                    [send_at:SendGrid\Personalization:private] => 
                )

            [1] => SendGrid\Personalization Object
                (
                    [tos:SendGrid\Personalization:private] => Array
                        (
                            [0] => SendGrid\Email Object
                                (
                                    [name:SendGrid\Email:private] => =?utf-8?B?TWljaGHFgiBQZXI=?=
                                    [email:SendGrid\Email:private] => michal.per@encja.com
                                )

                        )

                    [ccs:SendGrid\Personalization:private] => 
                    [bccs:SendGrid\Personalization:private] => 
                    [subject:SendGrid\Personalization:private] => 
                    [headers:SendGrid\Personalization:private] => 
                    [substitutions:SendGrid\Personalization:private] => Array
                        (
                            [-dmid-] => 7
                            [-cid-] => 696969
                            [-test-] => 1
                            [{firstName}] => First
                            [{lastName}] => Last
                            [{mail}] => michal.per@encja.com
                        )

                    [custom_args:SendGrid\Personalization:private] => 
                    [send_at:SendGrid\Personalization:private] => 
                )

        )

    [subject] => =?UTF-8?B?c3ViamVjdA==?=
    [contents] => Array
        (
            [0] => SendGrid\Content Object
                (
                    [type:SendGrid\Content:private] => text/plain
                    [value:SendGrid\Content:private] => {firstName} {lastName} {mail} test!
                )

            [1] => SendGrid\Content Object
                (
                    [type:SendGrid\Content:private] => text/html
                    [value:SendGrid\Content:private] => {firstName} {lastName} {mail} test!
                )

        )

    [attachments] => 
    [template_id] => 
    [sections] => 
    [headers] => 
    [categories] => 
    [custom_args] => Array
        (
            [cmrid] => 3
            [dmcid] => 69
            [env] => prod
            [dmid] => -dmid-
            [cid] => -cid-
            [test] => -test-
        )

    [send_at] => 
    [batch_id] => 
    [asm] => 
    [ip_pool_name] => 
    [mail_settings] => 
    [tracking_settings] => 
    [reply_to] => SendGrid\ReplyTo Object
        (
            [email:SendGrid\ReplyTo:private] => michal.per@ipresso.com
            [name:SendGrid\ReplyTo:private] => 
        )

)

Here is my example and response:
SendGrid\Response Object
(
    [statusCode:protected] => 400
    [body:protected] => {"errors":[{"message":"Bad Request","field":null,"help":null}]}
    [headers:protected] => Array
        (
            [0] => HTTP/1.1 400 Bad Request
            [1] => Server: nginx
            [2] => Date: Thu, 27 Jul 2017 06:02:41 GMT
            [3] => Content-Type: application/json
            [4] => Content-Length: 63
            [5] => Connection: keep-alive
            [6] => Access-Control-Allow-Origin: https://sendgrid.api-docs.io
            [7] => Access-Control-Allow-Methods: POST
            [8] => Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
            [9] => Access-Control-Max-Age: 600
            [10] => X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html
            [11] => 
            [12] => 
        )

)

**Comment by thinkingserious** [comment] 2017-07-27 06:14
@michalper,

Can you give me the [underlying error](https://github.com/sendgrid/sendgrid-php/blob/master/TROUBLESHOOTING.md#error)? 

I'm guessing the error is caused by not passing in strings as the values for the substitutions.

**Comment by michalper** [comment] 2017-07-27 06:25
@thinkingserious maybe I'm not understanding you, but version 6.0 don't throws any Exceptions.

This is my code example : 
`  try {
            $sg = new \SendGrid($this->apiKey);
            $ret = $sg->client->mail()->send()->post($this->mail);
            
        } catch (\Exception $e) {
            Tools::dump(1, $e->getMessage());
        }

        Tools::dump(1, $ret);`

and it always return $ret with SendGrid\Response Object. Is there any option to turn on exceptions in this lib version?

**Comment by thinkingserious** [comment] 2017-07-27 06:29
Ah, yes, we have an open bug for that, could you please try the workaround [here](https://github.com/sendgrid/sendgrid-php/issues/321#issuecomment-261660468).

Also, can you make sure all parameters are strings?

Thanks!

**Comment by michalper** [comment] 2017-07-27 06:38
@thinkingserious after convert integers to string I've got 202, but parameters aren't parsed in response:

[object] (stdClass: {**\"dmid\":\"-dmid-\"**,**\"test\":\"-test-\"**,\"ip\":\"167.89.55.65\",\"env\":\"prod\",\"response\":\"OK\",\"sg_message_id\":\"ZlwxsyOXTS6Rvaz2_fsjNw.filter0004p2mdw1-24105-597988A6-9.1\",\"sg_event_id\":\"ed-PLUZjRSemo1psJDLkzA\",\"event\":\"delivered\",\"tls\":1,\"email\":\"michal.per@encja.com\",\"smtp-id\":\"<ZlwxsyOXTS6Rvaz2_fsjNw@ismtpd0027p1mdw1.sendgrid.net>\",\"timestamp\":1501137064,\"dmcid\":\"69\",\"cid\":\"696969\",\"cmrid\":\"3\"})

**Comment by thinkingserious** [comment] 2017-07-27 15:49
Hi @michalper,

I apologize, I'm not quite sure what you mean by "parameters still aren't parsed in response".  Do you mean that you are looking for the object you provided to be converted to JSON or some other object? 

With Best Regards,

Elmer

**Comment by michalper** [comment] 2017-07-27 19:22
@thinkingserious 
In our email campaigns we have many as you say "custom arguments" for every message. For example **-dmid-** and **-test-**. Every message has different value of those arguments, but they are hidden and not shown in message content - we just want to have them in SendGrid Event Notifications (webhooks). 

In SMTPAPI they call as Unique Arguments (https://sendgrid.com/docs/API_Reference/SMTP_API/unique_arguments.html). In the last part of this document, there is information about how to use Substitution tags as Unique Arguments: **To apply different unique arguments to individual emails, you may use substitution tags.**

Actually we're using the 4.0.4 version of sendgrid/sendgrid library, because we have to send those unique args via SMTP API. 

So my question is: "How to send Substitution Tags as Unique Arguments using only sendgrid/sendgrid library in version 6.0.0?".

Is everything clear now? :)

**Comment by thinkingserious** [comment] 2017-07-28 18:35
Hi @michalper,

It looks like you found a bug that one of our support engineers will need to tackle. Please open up a ticket [here](https://support.sendgrid.com) to get started.

Sorry about the confusion.

With Best Regards,

Elmer

**Comment by czmarcos** [comment] 2018-03-08 20:12
@michalper did you solve this issue?

I'm sending my custom arguments as personalizations/substitutions through the API but I'm not receiving them back with the webhooks as well.

**Comment by michalper** [comment] 2018-03-09 06:45
Here is official response from SendGrid. I've forgotten to put it here, but yesterday I received mention from other user.

> Hi,
> 
> I apologize that our investigation took so long.
> 
> After some checks and investigations, our engineers informed us that the substitution tags shouldn't be used in unique arguments.
> 
> Here is where you can find in documentation that Substitutions will not be made on custom arguments, so any string that is entered into the custom_args parameter will be assumed to be the custom argument that you would like to be used.: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html > http://screencast.com/t/Dk4yfY4dFJ
> 
> Substitutions in custom arguments are totally random, that is why this has been considered an unsupported feature, also considering custom args can be replaced at the recipient personalization level.
> 
> 
> Useful link:
> https://s3.amazonaws.com/uploads.hipchat.com/17705/477959/V1VoKrUyBm6pOt1/v3_MailSend_Comparison_resized.png
> 

We've been using substitution tags as unique arguments for ~3 years via "sendgrid/sendgrid": "^4.0". Without them, Your newest API is completely useless for us. 

Greetings.

**Comment by thinkingserious** [comment] 2018-03-09 19:17
Thanks for the additional detail! I will report this to our product team internally for further investigation.

**Comment by michalper** [comment] 2018-05-21 05:07
Hi @thinkingserious,
can we send Substitution Tags as Unique Arguments using 7.x ?

**Comment by thinkingserious** [comment] 2018-05-22 01:56
Hello @michalper,

No. Unfortunately, this is an issue that needs to be addressed in the underlying API.

**Comment by michalper** [comment] 2018-05-22 05:32
@thinkingserious is there any option to use that feature using sendgrid/smtpapi ? 

We don't want to use version 4.0.4, but for us this is the last one working version.

**Comment by thinkingserious** [comment] 2018-05-22 17:12
Hello @michalper,

Version 4.0.4 is the last version of this SDK that supports the v2 of the SendGrid API. It will not be deprecated.

I'm not sure if our SMTP API can help, but [we do have an SDK](https://github.com/sendgrid/smtpapi-php) for it.

With Best Regards,

Elmer

**Comment by wwendorf** [comment] 2019-07-30 19:17
I need this functionality as well.  I am sending this to the APIv3 using curl.  This is the data I'm sending.

{
	"personalizations": [{
		"to": [{
			"email": "some@body.com",
			"name": "Some Body"
		}],
		"dynamic_template_data": {
			"unsubscribeLink": "http:\/\/some.url.com\/unsubscribe\/laksjdf0a939jfal3jkjfalksdjf="
		},
		"custom_args": {
			"unique_id": "jakljklhskjdfhiuwehofaiuwhfkjasdhflkasd"
		}
	}],
	"from": {
		"email": "noreply@somewhere.com",
		"name": "Somewhere Inc"
	},
	"reply_to": {
		"email": "noreply@somewhere.com",
		"name": "Somwhere Inc"
	},
	"template_id": "d-a679d81578a6c9e94"
}

Has any progress been made on this bug??? I've tried sending the custom_args in different locations as the api documentation has several references of where to put it.  

If I am sending it as JSON, is this right? If not, where should it go?  Or is it still broken?  If it's still broken, why isn't it fixed??

**Comment by eshanholtz** [comment] 2020-09-02 00:05
Closing this as it has been marked a non-library issue.

**Closed by eshanholtz** 2020-09-02 00:05 UTC
Labels: difficulty: unknown or n/a, type: non-library issue
