### ISSUE TITLE
Latest release .zip corrupt, SendGrid not compatible with PHP 8

### ISSUE THREAD

**Issue by gravity-ac** [sendgrid/sendgrid-php#1083] opened 2022-02-20 15:58 UTC
Issue Summary
---------------
SendGrid installed with Composer not working with PHP 8.
One suggested solution is manual install and referencing latest_version.zip.
However, the 7.11.4 release zip file is corrupt.

Exception/Log
--------------
caution:  zipfile comment truncated
error [sendgrid-php.zip]:  missing 6001492534 bytes in zipfile
  (attempting to process anyway)
error [sendgrid-php.zip]:  attempt to seek before beginning of zipfile
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

Technical details:
-----------------
* sendgrid-php version: 7.11.4
* php version: 8.0
* Ubuntu 20.04
* latest apache2

**Comment by childish-sambino** [comment] 2022-02-22 14:22
Duplicate of #1082

**Closed by childish-sambino** 2022-02-22 14:22 UTC
